<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tu chn sp xp sn phm_img6029</name>
   <tag></tag>
   <elementGuidId>a049ba30-5bda-4c2f-9780-7b72634301b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img6029</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img6029']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.vascara.com/uploads/cms_productmedia/2022/February/25/vi-cam-tay-mini-crescent-phoi-van-soc-wal-0225-mau-trang-main__63156__1645771324-medium@2x.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img6029</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Ví Cầm Tay Mini Crescent Phối Vân Sọc - WAL 0225 - Màu Trắng - vascara.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avatar before </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img6029&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img6029']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Ví Cầm Tay Mini Crescent Phối Vân Sọc - WAL 0225 - Màu Trắng - vascara.com']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.vascara.com/uploads/cms_productmedia/2022/February/25/vi-cam-tay-mini-crescent-phoi-van-soc-wal-0225-mau-trang-main__63156__1645771324-medium@2x.jpg' and @id = 'img6029' and @alt = 'Ví Cầm Tay Mini Crescent Phối Vân Sọc - WAL 0225 - Màu Trắng - vascara.com']</value>
   </webElementXpaths>
</WebElementEntity>
