<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Balo Np Gp Mu Kem Nhiu Ngn Phi Vin_img6183</name>
   <tag></tag>
   <elementGuidId>97c9727e-84c2-44cb-9f6d-22cef5d78415</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img6183</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img6183']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.vascara.com/uploads/cms_productmedia/2022/April/30/bac-0160-nav--1-__63507__1651315610-medium@2x.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img6183</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Balo Nắp Gập Màu Trắng Nhiều Ngăn Phối Viền - BAC 0160 - Màu Xanh Navy - vascara.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avatar before </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img6183&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img6183']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Balo Nắp Gập Màu Trắng Nhiều Ngăn Phối Viền - BAC 0160 - Màu Xanh Navy - vascara.com']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.vascara.com/uploads/cms_productmedia/2022/April/30/bac-0160-nav--1-__63507__1651315610-medium@2x.jpg' and @id = 'img6183' and @alt = 'Balo Nắp Gập Màu Trắng Nhiều Ngăn Phối Viền - BAC 0160 - Màu Xanh Navy - vascara.com']</value>
   </webElementXpaths>
</WebElementEntity>
