<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tu chn sp xp sn phm_img6184</name>
   <tag></tag>
   <elementGuidId>65490c0a-41a7-4c63-adc9-b00e9d27854f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img6184</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img6184']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.vascara.com/uploads/cms_productmedia/2022/May/4/1__63654__1651656405-medium@2x.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img6184</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Balo Nắp Gập Màu Kem Nhiều Ngăn Phối Viền - BAC 0160 - Màu Hồng - vascara.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avatar before </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img6184&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img6184']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Balo Nắp Gập Màu Kem Nhiều Ngăn Phối Viền - BAC 0160 - Màu Hồng - vascara.com']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.vascara.com/uploads/cms_productmedia/2022/May/4/1__63654__1651656405-medium@2x.jpg' and @id = 'img6184' and @alt = 'Balo Nắp Gập Màu Kem Nhiều Ngăn Phối Viền - BAC 0160 - Màu Hồng - vascara.com']</value>
   </webElementXpaths>
</WebElementEntity>
